// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.24.4
// source: common.proto

/* eslint-disable */

export const protobufPackage = "common";

/** 区服状态 */
export enum ServerStatus {
  /** MAINTENANCE - 维护中 */
  MAINTENANCE = 0,
  /** SMOOTH - 流畅 */
  SMOOTH = 1,
  /** CROWDED - 拥挤 */
  CROWDED = 2,
  /** FULL - 爆满 */
  FULL = 3,
  UNRECOGNIZED = -1,
}

/** 错误码定义 */
export enum ErrorCode {
  /** SUCCESS - 成功 */
  SUCCESS = 0,
  /** UNKNOWN_ERROR - 未知错误 */
  UNKNOWN_ERROR = 1,
  /** INVALID_REQUEST - 无效请求 */
  INVALID_REQUEST = 2,
  /** UNAUTHORIZED - 未授权 */
  UNAUTHORIZED = 3,
  /** FORBIDDEN - 禁止访问 */
  FORBIDDEN = 4,
  /** NOT_FOUND - 未找到 */
  NOT_FOUND = 5,
  /** TIMEOUT - 超时 */
  TIMEOUT = 6,
  /** INTERNAL_ERROR - 内部错误 */
  INTERNAL_ERROR = 7,
  /** SERVICE_UNAVAILABLE - 服务不可用 */
  SERVICE_UNAVAILABLE = 8,
  /** ACCOUNT_NOT_FOUND - 账号相关错误 (100-199) */
  ACCOUNT_NOT_FOUND = 100,
  /** PASSWORD_ERROR - 密码错误 */
  PASSWORD_ERROR = 101,
  /** ACCOUNT_BANNED - 账号被封禁 */
  ACCOUNT_BANNED = 102,
  /** ACCOUNT_ALREADY_EXISTS - 账号已存在 */
  ACCOUNT_ALREADY_EXISTS = 103,
  /** INVALID_ACCOUNT_FORMAT - 账号格式错误 */
  INVALID_ACCOUNT_FORMAT = 104,
  /** INVALID_PASSWORD_FORMAT - 密码格式错误 */
  INVALID_PASSWORD_FORMAT = 105,
  /** ROLE_NOT_FOUND - 角色相关错误 (200-299) */
  ROLE_NOT_FOUND = 200,
  /** ROLE_NAME_EXISTS - 角色名已存在 */
  ROLE_NAME_EXISTS = 201,
  /** ROLE_COUNT_LIMIT - 角色数量达到上限 */
  ROLE_COUNT_LIMIT = 202,
  /** INVALID_ROLE_NAME - 角色名格式错误 */
  INVALID_ROLE_NAME = 203,
  /** ROLE_NAME_TOO_SHORT - 角色名太短 */
  ROLE_NAME_TOO_SHORT = 204,
  /** ROLE_NAME_TOO_LONG - 角色名太长 */
  ROLE_NAME_TOO_LONG = 205,
  /** ROLE_NAME_SENSITIVE - 角色名包含敏感词 */
  ROLE_NAME_SENSITIVE = 206,
  /** SERVER_NOT_FOUND - 区服相关错误 (300-399) */
  SERVER_NOT_FOUND = 300,
  /** SERVER_MAINTENANCE - 区服维护中 */
  SERVER_MAINTENANCE = 301,
  /** SERVER_FULL - 区服已满 */
  SERVER_FULL = 302,
  UNRECOGNIZED = -1,
}

/**
 * 通用消息包装
 * 所有消息都通过这个结构发送
 */
export interface Packet {
  /** 消息ID */
  msg_id: number;
  /** 会话ID（用于请求响应匹配） */
  session: number;
  /** 消息体（具体消息的序列化数据） */
  data: Uint8Array;
  /** 时间戳 */
  timestamp: number;
}

/** 通用响应 */
export interface Response {
  /** 错误码 */
  code: ErrorCode;
  /** 错误信息 */
  message: string;
  /** 响应数据 */
  data: Uint8Array;
}
