// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.24.4
// source: game.proto

/* eslint-disable */
import type { ErrorCode } from "./common";

export const protobufPackage = "game";

/** 完整角色信息（进入游戏后返回） */
export interface FullRoleInfo {
  /** 角色ID */
  role_id: number;
  /** 角色名 */
  role_name: string;
  /** 等级 */
  level: number;
  /** 经验值 */
  exp: number;
  /** 头像ID */
  avatar_id: number;
  /** 金币 */
  gold: number;
  /** 钻石 */
  diamond: number;
  /** 总战力 */
  total_power: number;
  /** VIP等级 */
  vip_level: number;
  /** 创建时间 */
  create_time: number;
  /** 上次登录时间 */
  last_login_time: number;
}

/** 道具信息 */
export interface ItemInfo {
  /** 道具ID */
  item_id: number;
  /** 数量 */
  count: number;
}

/** 任务信息 */
export interface TaskInfo {
  /** 任务ID */
  task_id: number;
  /** 状态：0未接 1进行中 2已完成 */
  status: number;
  /** 进度 */
  progress: number;
}

/** 进入游戏请求（选择已有角色） */
export interface EnterGameRequest {
  /** 角色ID */
  role_id: number;
}

/** 进入游戏响应 */
export interface EnterGameResponse {
  code: ErrorCode;
  message: string;
  /** 完整角色信息 */
  role_info?:
    | FullRoleInfo
    | undefined;
  /** 背包道具 */
  items: ItemInfo[];
  /** 任务列表 */
  tasks: TaskInfo[];
  /** 服务器时间 */
  server_time: number;
}

/** 创建角色请求 */
export interface CreateRoleRequest {
  /** 角色名 */
  role_name: string;
}

/**
 * 创建角色响应
 * 创建成功后直接返回角色信息，自动进入游戏
 */
export interface CreateRoleResponse {
  code: ErrorCode;
  message: string;
  /** 新创建的角色信息 */
  role_info?:
    | FullRoleInfo
    | undefined;
  /** 初始道具 */
  items: ItemInfo[];
  /** 初始任务 */
  tasks: TaskInfo[];
  /** 服务器时间 */
  server_time: number;
}
