// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.24.4
// source: message_id.proto

/* eslint-disable */

export const protobufPackage = "protocol";

/**
 * 消息ID映射表
 * 用于消息路由和识别
 */
export enum MessageId {
  UNKNOWN = 0,
  /** PING - 系统消息 (1-99) */
  PING = 1,
  PONG = 2,
  /** GATEWAY_HEARTBEAT_REQ - Gateway消息 (100-199) */
  GATEWAY_HEARTBEAT_REQ = 100,
  GATEWAY_HEARTBEAT_RSP = 101,
  GATEWAY_CONNECT_REQ = 102,
  GATEWAY_CONNECT_RSP = 103,
  GATEWAY_DISCONNECT_NOTIFY = 104,
  /** LOGIN_ACCOUNT_LOGIN_REQ - Login消息 (200-299) */
  LOGIN_ACCOUNT_LOGIN_REQ = 210,
  LOGIN_ACCOUNT_LOGIN_RSP = 211,
  LOGIN_SELECT_SERVER_REQ = 212,
  LOGIN_SELECT_SERVER_RSP = 213,
  /** SERVER_GET_LIST_REQ - Server消息 (250-299) */
  SERVER_GET_LIST_REQ = 250,
  SERVER_GET_LIST_RSP = 251,
  SERVER_STATUS_UPDATE = 252,
  /** GAME_ENTER_GAME_REQ - Game消息 (300-399) */
  GAME_ENTER_GAME_REQ = 320,
  GAME_ENTER_GAME_RSP = 321,
  GAME_CREATE_ROLE_REQ = 322,
  GAME_CREATE_ROLE_RSP = 323,
  UNRECOGNIZED = -1,
}
