local ____lualib = require("lualib_bundle")
local __TS__SourceMapTraceBack = ____lualib.__TS__SourceMapTraceBack
__TS__SourceMapTraceBack(debug.getinfo(1).short_src, {["5"] = 9,["7"] = 12,["8"] = 14,["9"] = 14,["10"] = 16,["11"] = 16,["12"] = 18,["13"] = 18,["14"] = 20,["15"] = 20,["16"] = 21,["17"] = 21,["19"] = 25,["20"] = 27,["21"] = 27,["22"] = 29,["23"] = 29,["24"] = 31,["25"] = 31,["26"] = 33,["27"] = 33,["28"] = 35,["29"] = 35,["30"] = 37,["31"] = 37,["32"] = 39,["33"] = 39,["34"] = 41,["35"] = 41,["36"] = 43,["37"] = 43,["38"] = 45,["39"] = 45,["40"] = 47,["41"] = 47,["42"] = 49,["43"] = 49,["44"] = 51,["45"] = 51,["46"] = 53,["47"] = 53,["48"] = 55,["49"] = 55,["50"] = 57,["51"] = 57,["52"] = 59,["53"] = 59,["54"] = 61,["55"] = 61,["56"] = 63,["57"] = 63,["58"] = 65,["59"] = 65,["60"] = 67,["61"] = 67,["62"] = 69,["63"] = 69,["64"] = 71,["65"] = 71,["66"] = 73,["67"] = 73,["68"] = 75,["69"] = 75,["70"] = 76,["71"] = 76});
local ____exports = {}
____exports.protobufPackage = "common"
--- 区服状态
____exports.ServerStatus = ____exports.ServerStatus or ({})
____exports.ServerStatus.MAINTENANCE = 0
____exports.ServerStatus[____exports.ServerStatus.MAINTENANCE] = "MAINTENANCE"
____exports.ServerStatus.SMOOTH = 1
____exports.ServerStatus[____exports.ServerStatus.SMOOTH] = "SMOOTH"
____exports.ServerStatus.CROWDED = 2
____exports.ServerStatus[____exports.ServerStatus.CROWDED] = "CROWDED"
____exports.ServerStatus.FULL = 3
____exports.ServerStatus[____exports.ServerStatus.FULL] = "FULL"
____exports.ServerStatus.UNRECOGNIZED = -1
____exports.ServerStatus[____exports.ServerStatus.UNRECOGNIZED] = "UNRECOGNIZED"
--- 错误码定义
____exports.ErrorCode = ____exports.ErrorCode or ({})
____exports.ErrorCode.SUCCESS = 0
____exports.ErrorCode[____exports.ErrorCode.SUCCESS] = "SUCCESS"
____exports.ErrorCode.UNKNOWN_ERROR = 1
____exports.ErrorCode[____exports.ErrorCode.UNKNOWN_ERROR] = "UNKNOWN_ERROR"
____exports.ErrorCode.INVALID_REQUEST = 2
____exports.ErrorCode[____exports.ErrorCode.INVALID_REQUEST] = "INVALID_REQUEST"
____exports.ErrorCode.UNAUTHORIZED = 3
____exports.ErrorCode[____exports.ErrorCode.UNAUTHORIZED] = "UNAUTHORIZED"
____exports.ErrorCode.FORBIDDEN = 4
____exports.ErrorCode[____exports.ErrorCode.FORBIDDEN] = "FORBIDDEN"
____exports.ErrorCode.NOT_FOUND = 5
____exports.ErrorCode[____exports.ErrorCode.NOT_FOUND] = "NOT_FOUND"
____exports.ErrorCode.TIMEOUT = 6
____exports.ErrorCode[____exports.ErrorCode.TIMEOUT] = "TIMEOUT"
____exports.ErrorCode.INTERNAL_ERROR = 7
____exports.ErrorCode[____exports.ErrorCode.INTERNAL_ERROR] = "INTERNAL_ERROR"
____exports.ErrorCode.SERVICE_UNAVAILABLE = 8
____exports.ErrorCode[____exports.ErrorCode.SERVICE_UNAVAILABLE] = "SERVICE_UNAVAILABLE"
____exports.ErrorCode.ACCOUNT_NOT_FOUND = 100
____exports.ErrorCode[____exports.ErrorCode.ACCOUNT_NOT_FOUND] = "ACCOUNT_NOT_FOUND"
____exports.ErrorCode.PASSWORD_ERROR = 101
____exports.ErrorCode[____exports.ErrorCode.PASSWORD_ERROR] = "PASSWORD_ERROR"
____exports.ErrorCode.ACCOUNT_BANNED = 102
____exports.ErrorCode[____exports.ErrorCode.ACCOUNT_BANNED] = "ACCOUNT_BANNED"
____exports.ErrorCode.ACCOUNT_ALREADY_EXISTS = 103
____exports.ErrorCode[____exports.ErrorCode.ACCOUNT_ALREADY_EXISTS] = "ACCOUNT_ALREADY_EXISTS"
____exports.ErrorCode.INVALID_ACCOUNT_FORMAT = 104
____exports.ErrorCode[____exports.ErrorCode.INVALID_ACCOUNT_FORMAT] = "INVALID_ACCOUNT_FORMAT"
____exports.ErrorCode.INVALID_PASSWORD_FORMAT = 105
____exports.ErrorCode[____exports.ErrorCode.INVALID_PASSWORD_FORMAT] = "INVALID_PASSWORD_FORMAT"
____exports.ErrorCode.ROLE_NOT_FOUND = 200
____exports.ErrorCode[____exports.ErrorCode.ROLE_NOT_FOUND] = "ROLE_NOT_FOUND"
____exports.ErrorCode.ROLE_NAME_EXISTS = 201
____exports.ErrorCode[____exports.ErrorCode.ROLE_NAME_EXISTS] = "ROLE_NAME_EXISTS"
____exports.ErrorCode.ROLE_COUNT_LIMIT = 202
____exports.ErrorCode[____exports.ErrorCode.ROLE_COUNT_LIMIT] = "ROLE_COUNT_LIMIT"
____exports.ErrorCode.INVALID_ROLE_NAME = 203
____exports.ErrorCode[____exports.ErrorCode.INVALID_ROLE_NAME] = "INVALID_ROLE_NAME"
____exports.ErrorCode.ROLE_NAME_TOO_SHORT = 204
____exports.ErrorCode[____exports.ErrorCode.ROLE_NAME_TOO_SHORT] = "ROLE_NAME_TOO_SHORT"
____exports.ErrorCode.ROLE_NAME_TOO_LONG = 205
____exports.ErrorCode[____exports.ErrorCode.ROLE_NAME_TOO_LONG] = "ROLE_NAME_TOO_LONG"
____exports.ErrorCode.ROLE_NAME_SENSITIVE = 206
____exports.ErrorCode[____exports.ErrorCode.ROLE_NAME_SENSITIVE] = "ROLE_NAME_SENSITIVE"
____exports.ErrorCode.SERVER_NOT_FOUND = 300
____exports.ErrorCode[____exports.ErrorCode.SERVER_NOT_FOUND] = "SERVER_NOT_FOUND"
____exports.ErrorCode.SERVER_MAINTENANCE = 301
____exports.ErrorCode[____exports.ErrorCode.SERVER_MAINTENANCE] = "SERVER_MAINTENANCE"
____exports.ErrorCode.SERVER_FULL = 302
____exports.ErrorCode[____exports.ErrorCode.SERVER_FULL] = "SERVER_FULL"
____exports.ErrorCode.UNRECOGNIZED = -1
____exports.ErrorCode[____exports.ErrorCode.UNRECOGNIZED] = "UNRECOGNIZED"
return ____exports
