local ____lualib = require("lualib_bundle")
local __TS__SourceMapTraceBack = ____lualib.__TS__SourceMapTraceBack
__TS__SourceMapTraceBack(debug.getinfo(1).short_src, {["5"] = 9,["8"] = 15,["9"] = 16,["10"] = 16,["11"] = 18,["12"] = 18,["13"] = 19,["14"] = 19,["15"] = 21,["16"] = 21,["17"] = 22,["18"] = 22,["19"] = 23,["20"] = 23,["21"] = 24,["22"] = 24,["23"] = 25,["24"] = 25,["25"] = 27,["26"] = 27,["27"] = 28,["28"] = 28,["29"] = 29,["30"] = 29,["31"] = 30,["32"] = 30,["33"] = 32,["34"] = 32,["35"] = 33,["36"] = 33,["37"] = 34,["38"] = 34,["39"] = 36,["40"] = 36,["41"] = 37,["42"] = 37,["43"] = 38,["44"] = 38,["45"] = 39,["46"] = 39,["47"] = 40,["48"] = 40});
local ____exports = {}
____exports.protobufPackage = "protocol"
--- 消息ID映射表
-- 用于消息路由和识别
____exports.MessageId = ____exports.MessageId or ({})
____exports.MessageId.UNKNOWN = 0
____exports.MessageId[____exports.MessageId.UNKNOWN] = "UNKNOWN"
____exports.MessageId.PING = 1
____exports.MessageId[____exports.MessageId.PING] = "PING"
____exports.MessageId.PONG = 2
____exports.MessageId[____exports.MessageId.PONG] = "PONG"
____exports.MessageId.GATEWAY_HEARTBEAT_REQ = 100
____exports.MessageId[____exports.MessageId.GATEWAY_HEARTBEAT_REQ] = "GATEWAY_HEARTBEAT_REQ"
____exports.MessageId.GATEWAY_HEARTBEAT_RSP = 101
____exports.MessageId[____exports.MessageId.GATEWAY_HEARTBEAT_RSP] = "GATEWAY_HEARTBEAT_RSP"
____exports.MessageId.GATEWAY_CONNECT_REQ = 102
____exports.MessageId[____exports.MessageId.GATEWAY_CONNECT_REQ] = "GATEWAY_CONNECT_REQ"
____exports.MessageId.GATEWAY_CONNECT_RSP = 103
____exports.MessageId[____exports.MessageId.GATEWAY_CONNECT_RSP] = "GATEWAY_CONNECT_RSP"
____exports.MessageId.GATEWAY_DISCONNECT_NOTIFY = 104
____exports.MessageId[____exports.MessageId.GATEWAY_DISCONNECT_NOTIFY] = "GATEWAY_DISCONNECT_NOTIFY"
____exports.MessageId.LOGIN_ACCOUNT_LOGIN_REQ = 210
____exports.MessageId[____exports.MessageId.LOGIN_ACCOUNT_LOGIN_REQ] = "LOGIN_ACCOUNT_LOGIN_REQ"
____exports.MessageId.LOGIN_ACCOUNT_LOGIN_RSP = 211
____exports.MessageId[____exports.MessageId.LOGIN_ACCOUNT_LOGIN_RSP] = "LOGIN_ACCOUNT_LOGIN_RSP"
____exports.MessageId.LOGIN_SELECT_SERVER_REQ = 212
____exports.MessageId[____exports.MessageId.LOGIN_SELECT_SERVER_REQ] = "LOGIN_SELECT_SERVER_REQ"
____exports.MessageId.LOGIN_SELECT_SERVER_RSP = 213
____exports.MessageId[____exports.MessageId.LOGIN_SELECT_SERVER_RSP] = "LOGIN_SELECT_SERVER_RSP"
____exports.MessageId.SERVER_GET_LIST_REQ = 250
____exports.MessageId[____exports.MessageId.SERVER_GET_LIST_REQ] = "SERVER_GET_LIST_REQ"
____exports.MessageId.SERVER_GET_LIST_RSP = 251
____exports.MessageId[____exports.MessageId.SERVER_GET_LIST_RSP] = "SERVER_GET_LIST_RSP"
____exports.MessageId.SERVER_STATUS_UPDATE = 252
____exports.MessageId[____exports.MessageId.SERVER_STATUS_UPDATE] = "SERVER_STATUS_UPDATE"
____exports.MessageId.GAME_ENTER_GAME_REQ = 320
____exports.MessageId[____exports.MessageId.GAME_ENTER_GAME_REQ] = "GAME_ENTER_GAME_REQ"
____exports.MessageId.GAME_ENTER_GAME_RSP = 321
____exports.MessageId[____exports.MessageId.GAME_ENTER_GAME_RSP] = "GAME_ENTER_GAME_RSP"
____exports.MessageId.GAME_CREATE_ROLE_REQ = 322
____exports.MessageId[____exports.MessageId.GAME_CREATE_ROLE_REQ] = "GAME_CREATE_ROLE_REQ"
____exports.MessageId.GAME_CREATE_ROLE_RSP = 323
____exports.MessageId[____exports.MessageId.GAME_CREATE_ROLE_RSP] = "GAME_CREATE_ROLE_RSP"
____exports.MessageId.UNRECOGNIZED = -1
____exports.MessageId[____exports.MessageId.UNRECOGNIZED] = "UNRECOGNIZED"
return ____exports
