// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message_id.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from message_id.proto</summary>
  public static partial class MessageIdReflection {

    #region Descriptor
    /// <summary>File descriptor for message_id.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBtZXNzYWdlX2lkLnByb3RvEghwcm90b2NvbCr9AwoJTWVzc2FnZUlkEgsK",
            "B1VOS05PV04QABIICgRQSU5HEAESCAoEUE9ORxACEhkKFUdBVEVXQVlfSEVB",
            "UlRCRUFUX1JFURBkEhkKFUdBVEVXQVlfSEVBUlRCRUFUX1JTUBBlEhcKE0dB",
            "VEVXQVlfQ09OTkVDVF9SRVEQZhIXChNHQVRFV0FZX0NPTk5FQ1RfUlNQEGcS",
            "HQoZR0FURVdBWV9ESVNDT05ORUNUX05PVElGWRBoEhcKE0dBVEVXQVlfS0lD",
            "S19OT1RJRlkQaRIcChdMT0dJTl9BQ0NPVU5UX0xPR0lOX1JFURDSARIcChdM",
            "T0dJTl9BQ0NPVU5UX0xPR0lOX1JTUBDTARIcChdMT0dJTl9TRUxFQ1RfU0VS",
            "VkVSX1JFURDUARIcChdMT0dJTl9TRUxFQ1RfU0VSVkVSX1JTUBDVARIYChNT",
            "RVJWRVJfR0VUX0xJU1RfUkVREPoBEhgKE1NFUlZFUl9HRVRfTElTVF9SU1AQ",
            "+wESGQoUU0VSVkVSX1NUQVRVU19VUERBVEUQ/AESGAoTR0FNRV9FTlRFUl9H",
            "QU1FX1JFURDAAhIYChNHQU1FX0VOVEVSX0dBTUVfUlNQEMECEhkKFEdBTUVf",
            "Q1JFQVRFX1JPTEVfUkVREMICEhkKFEdBTUVfQ1JFQVRFX1JPTEVfUlNQEMMC",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.MessageId), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///*
  /// 消息ID映射表
  /// 用于消息路由和识别
  /// </summary>
  public enum MessageId {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    /// <summary>
    /// 系统消息 (1-99)
    /// </summary>
    [pbr::OriginalName("PING")] Ping = 1,
    [pbr::OriginalName("PONG")] Pong = 2,
    /// <summary>
    /// Gateway消息 (100-199)
    /// </summary>
    [pbr::OriginalName("GATEWAY_HEARTBEAT_REQ")] GatewayHeartbeatReq = 100,
    [pbr::OriginalName("GATEWAY_HEARTBEAT_RSP")] GatewayHeartbeatRsp = 101,
    [pbr::OriginalName("GATEWAY_CONNECT_REQ")] GatewayConnectReq = 102,
    [pbr::OriginalName("GATEWAY_CONNECT_RSP")] GatewayConnectRsp = 103,
    [pbr::OriginalName("GATEWAY_DISCONNECT_NOTIFY")] GatewayDisconnectNotify = 104,
    [pbr::OriginalName("GATEWAY_KICK_NOTIFY")] GatewayKickNotify = 105,
    /// <summary>
    /// Login消息 (200-299)
    /// </summary>
    [pbr::OriginalName("LOGIN_ACCOUNT_LOGIN_REQ")] LoginAccountLoginReq = 210,
    [pbr::OriginalName("LOGIN_ACCOUNT_LOGIN_RSP")] LoginAccountLoginRsp = 211,
    [pbr::OriginalName("LOGIN_SELECT_SERVER_REQ")] LoginSelectServerReq = 212,
    [pbr::OriginalName("LOGIN_SELECT_SERVER_RSP")] LoginSelectServerRsp = 213,
    /// <summary>
    /// Server消息 (250-299)
    /// </summary>
    [pbr::OriginalName("SERVER_GET_LIST_REQ")] ServerGetListReq = 250,
    [pbr::OriginalName("SERVER_GET_LIST_RSP")] ServerGetListRsp = 251,
    [pbr::OriginalName("SERVER_STATUS_UPDATE")] ServerStatusUpdate = 252,
    /// <summary>
    /// Game消息 (300-399)
    /// </summary>
    [pbr::OriginalName("GAME_ENTER_GAME_REQ")] GameEnterGameReq = 320,
    [pbr::OriginalName("GAME_ENTER_GAME_RSP")] GameEnterGameRsp = 321,
    [pbr::OriginalName("GAME_CREATE_ROLE_REQ")] GameCreateRoleReq = 322,
    [pbr::OriginalName("GAME_CREATE_ROLE_RSP")] GameCreateRoleRsp = 323,
  }

  #endregion

}

#endregion Designer generated code
