<Project Sdk="Godot.NET.Sdk/4.6.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>ClinetCSharp</RootNamespace>
    <LangVersion>12.0</LangVersion>
    <Nullable>annotations</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="tools\**" />
    <Compile Remove="TempGenerated\**" />
    <Compile Remove="ClinetCSharp.Tests\**" />
    <EmbeddedResource Remove="tools\**" />
    <EmbeddedResource Remove="TempGenerated\**" />
    <EmbeddedResource Remove="ClinetCSharp.Tests\**" />
    <None Remove="tools\**" />
    <None Remove="TempGenerated\**" />
    <None Remove="ClinetCSharp.Tests\**" />
  </ItemGroup>
</Project>
