<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\GameServer.Proto\GameServer.Proto.csproj" />
    <ProjectReference Include="..\GameServer.Tables\GameServer.Tables.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
  </ItemGroup>
</Project>
