
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------


local enums =
{
    ---@class AudioType
     ---@field public UNKNOWN integer
     ---@field public ACC integer
     ---@field public AIFF integer
    ['AudioType'] = {   UNKNOWN=0,  ACC=1,  AIFF=2,  };
    ---@class common.EBoolOperator
     ---@field public AND integer
     ---@field public OR integer
    ['common.EBoolOperator'] = {   AND=0,  OR=1,  };
    ---@class common.EMonsterAttr
     ---@field public HP integer @生命值
     ---@field public ATK integer @攻击力
     ---@field public DEF integer @防御力
    ['common.EMonsterAttr'] = {   HP=1,  ATK=2,  DEF=3,  };
    ---@class item.EClothersStarQualityType
     ---@field public ONE integer @一星
     ---@field public TWO integer @二星
     ---@field public THREE integer @三星
     ---@field public FOUR integer @四星
     ---@field public FIVE integer @五星
     ---@field public SIX integer @六星
     ---@field public SEVEN integer @七星
     ---@field public EIGHT integer @八星
     ---@field public NINE integer @九星
     ---@field public TEN integer @十星
    ['item.EClothersStarQualityType'] = {   ONE=1,  TWO=2,  THREE=3,  FOUR=4,  FIVE=5,  SIX=6,  SEVEN=7,  EIGHT=8,  NINE=9,  TEN=10,  };
    ---@class item.EClothersTag
     ---@field public FANG_SHAI integer @防晒
     ---@field public WU_ZHE integer @舞者
    ['item.EClothersTag'] = {   FANG_SHAI=1,  WU_ZHE=2,  };
    ---@class item.EClothesHidePartType
     ---@field public CHEST integer @胸部
     ---@field public HEAD integer @手
     ---@field public SPINE_UPPER integer @脊柱上
     ---@field public SPINE_LOWER integer @脊柱下
     ---@field public HIP integer @臀部
     ---@field public LEG_UPPER integer @腿上
     ---@field public LEG_MIDDLE integer @腿中
     ---@field public LEG_LOWER integer @腿下
    ['item.EClothesHidePartType'] = {   CHEST=0,  HEAD=1,  SPINE_UPPER=2,  SPINE_LOWER=3,  HIP=4,  LEG_UPPER=5,  LEG_MIDDLE=6,  LEG_LOWER=7,  };
    ---@class item.EClothesPropertyType
     ---@field public JIAN_YUE integer @简约
     ---@field public HUA_LI integer @华丽
     ---@field public KE_AI integer @可爱
     ---@field public CHENG_SHU integer @成熟
     ---@field public HUO_PO integer @活泼
     ---@field public YOU_YA integer @优雅
     ---@field public QING_CHUN integer @清纯
     ---@field public XING_GAN integer @性感
     ---@field public QING_LIANG integer @清凉
     ---@field public BAO_NUAN integer @保暖
    ['item.EClothesPropertyType'] = {   JIAN_YUE=1,  HUA_LI=2,  KE_AI=3,  CHENG_SHU=4,  HUO_PO=5,  YOU_YA=6,  QING_CHUN=7,  XING_GAN=8,  QING_LIANG=9,  BAO_NUAN=10,  };
    ---@class item.ECurrencyType
     ---@field public DIAMOND integer @钻石
     ---@field public GOLD integer @金币
     ---@field public SILVER integer @银币
     ---@field public EXP integer @经验
     ---@field public POWER_POINT integer @能量点
    ['item.ECurrencyType'] = {   DIAMOND=1,  GOLD=2,  SILVER=3,  EXP=4,  POWER_POINT=5,  };
    ---@class item.EItemQuality @道具品质
     ---@field public WHITE integer @白
     ---@field public GREEN integer @绿
     ---@field public BLUE integer @蓝
     ---@field public PURPLE integer @紫
     ---@field public GOLDEN integer @金
    ['item.EItemQuality'] = {   WHITE=0,  GREEN=1,  BLUE=2,  PURPLE=3,  GOLDEN=4,  };
    ---@class item.EMajorType
     ---@field public CURRENCY integer @货币
     ---@field public CLOTH integer @服装
     ---@field public QUEST integer @任务
     ---@field public CONSUMABLES integer @消耗品
     ---@field public TREASURE_BOX integer @宝箱
     ---@field public ACHIEVEMENT_AND_TITLE integer @成就和称谓
     ---@field public HEAD_FRAME integer @头像框
     ---@field public VOICE integer @语音
     ---@field public ACTION integer @动作
     ---@field public EXPANSION integer @扩容道具
     ---@field public MATERIAL integer @制作材料
    ['item.EMajorType'] = {   CURRENCY=1,  CLOTH=2,  QUEST=3,  CONSUMABLES=4,  TREASURE_BOX=5,  ACHIEVEMENT_AND_TITLE=6,  HEAD_FRAME=7,  VOICE=8,  ACTION=9,  EXPANSION=10,  MATERIAL=11,  };
    ---@class item.EMinorType
     ---@field public DIAMOND integer @钻石
     ---@field public GOLD integer @金币
     ---@field public SILVER integer @银币
     ---@field public EXP integer @经验
     ---@field public POWER_POINT integer @能量点
     ---@field public HAIR_STYLE integer @发型
     ---@field public COAT integer @外套
     ---@field public UPPER_JACKET integer @上衣
     ---@field public TROUSERS integer @裤子
     ---@field public SKIRT integer @裙子
     ---@field public SOCKS integer @袜子
     ---@field public SHOES integer @鞋子
     ---@field public HAIR_ACCESSORY integer @发饰
     ---@field public HAT integer @帽子
     ---@field public EARRING integer @耳饰
     ---@field public NECKLACE integer @颈饰
     ---@field public BRACELET integer @腕饰
     ---@field public HAIR_CLASP integer @发箍
     ---@field public GLOVE integer @手套
     ---@field public HANDHELD_OBJECT integer @手持物
     ---@field public SPECIAL integer @特殊
     ---@field public BASE_COSMETIC integer @底妆
     ---@field public EYEBROW_COSMETIC integer @眉妆
     ---@field public EYELASH integer @睫毛
     ---@field public COSMETIC_CONTACT_LENSES integer @美瞳
     ---@field public LIP_COSMETIC integer @唇妆
     ---@field public SKIN_COLOR integer @肤色
     ---@field public ONE_PIECE_DRESS integer @连衣裙
     ---@field public SWITCH_CLOTHES_SCENE integer @换装场景
     ---@field public QUEST integer @任务道具
     ---@field public CAST integer @投掷物
     ---@field public SWORD integer @刀剑
     ---@field public BOW_ARROW integer @弓箭
     ---@field public WANDS integer @法杖
     ---@field public SPECIAL_TOOL integer @特殊工具
     ---@field public FOOD integer @食物
     ---@field public TREASURE_BOX integer @宝箱
     ---@field public KEY integer @钥匙
     ---@field public MULTI_CHOOSE_TREASURE_BOX integer @多选一宝箱
     ---@field public ACHIEVEMENT integer @成就相关
     ---@field public TITLE integer @称谓相关
     ---@field public AVATAR_FRAME integer @头像框
     ---@field public VOICE integer @语音
     ---@field public IDLE_POSE integer @特殊待机动作
     ---@field public PHOTO_POSE integer @拍照动作
     ---@field public BAG integer @背包
     ---@field public FRIEND_CAPACITY integer @好友数量
     ---@field public CONSTRUCTION_MATERIAL integer @制作材料
     ---@field public DESIGN_DRAWING integer @设计图纸
    ['item.EMinorType'] = {   DIAMOND=101,  GOLD=102,  SILVER=103,  EXP=104,  POWER_POINT=105,  HAIR_STYLE=210,  COAT=220,  UPPER_JACKET=230,  TROUSERS=241,  SKIRT=242,  SOCKS=250,  SHOES=260,  HAIR_ACCESSORY=271,  HAT=272,  EARRING=273,  NECKLACE=274,  BRACELET=275,  HAIR_CLASP=276,  GLOVE=277,  HANDHELD_OBJECT=278,  SPECIAL=279,  BASE_COSMETIC=281,  EYEBROW_COSMETIC=282,  EYELASH=283,  COSMETIC_CONTACT_LENSES=284,  LIP_COSMETIC=285,  SKIN_COLOR=286,  ONE_PIECE_DRESS=290,  SWITCH_CLOTHES_SCENE=291,  QUEST=301,  CAST=401,  SWORD=421,  BOW_ARROW=422,  WANDS=423,  SPECIAL_TOOL=424,  FOOD=403,  TREASURE_BOX=501,  KEY=502,  MULTI_CHOOSE_TREASURE_BOX=503,  ACHIEVEMENT=601,  TITLE=602,  AVATAR_FRAME=701,  VOICE=801,  IDLE_POSE=901,  PHOTO_POSE=902,  BAG=1001,  FRIEND_CAPACITY=1002,  CONSTRUCTION_MATERIAL=1101,  DESIGN_DRAWING=1102,  };
    ---@class item.EUseType
     ---@field public MANUAL integer @手动
     ---@field public AUTO integer @自动
    ['item.EUseType'] = {   MANUAL=0,  AUTO=1,  };
    ---@class test.AccessFlag
     ---@field public WRITE integer
     ---@field public READ integer
     ---@field public TRUNCATE integer
     ---@field public NEW integer
     ---@field public READ_WRITE integer
    ['test.AccessFlag'] = {   WRITE=1,  READ=2,  TRUNCATE=4,  NEW=8,  READ_WRITE=3,  };
    ---@class test.ETestQuality
     ---@field public A integer @最高品质
     ---@field public B integer @黑色的
     ---@field public C integer @蓝色的
     ---@field public D integer @最差品质
    ['test.ETestQuality'] = {   A=1,  B=2,  C=3,  D=4,  };
}

local beans = {}
    do
    ---@class AccountConfig  @账号配置数据结构
     ---@field public id integer @配置ID
     ---@field public max_role_count integer @最大角色数
     ---@field public role_name_min_len integer @角色名最小长度
     ---@field public role_name_max_len integer @角色名最大长度
     ---@field public init_level integer @初始等级
     ---@field public init_gold integer @初始金币
     ---@field public init_diamond integer @初始钻石
     ---@field public init_avatar_id integer @初始头像ID
        local class = {
            { name='id', type='integer'},
            { name='max_role_count', type='integer'},
            { name='role_name_min_len', type='integer'},
            { name='role_name_max_len', type='integer'},
            { name='init_level', type='integer'},
            { name='init_gold', type='integer'},
            { name='init_diamond', type='integer'},
            { name='init_avatar_id', type='integer'},
        }
        beans['AccountConfig'] = class
    end
    do
    ---@class common.AccountConfig 
     ---@field public id integer @配置ID
     ---@field public max_role_count integer @最大角色数
     ---@field public role_name_min_len integer @角色名最小长度
     ---@field public role_name_max_len integer @角色名最大长度
     ---@field public init_level integer @初始等级
     ---@field public init_gold integer @初始金币
     ---@field public init_diamond integer @初始钻石
     ---@field public init_avatar_id integer @初始头像ID
        local class = {
            { name='id', type='integer'},
            { name='max_role_count', type='integer'},
            { name='role_name_min_len', type='integer'},
            { name='role_name_max_len', type='integer'},
            { name='init_level', type='integer'},
            { name='init_gold', type='integer'},
            { name='init_diamond', type='integer'},
            { name='init_avatar_id', type='integer'},
        }
        beans['common.AccountConfig'] = class
    end
    do
    ---@class common.Ai 
     ---@field public id integer @AI配置ID
     ---@field public ai_type string @AI类型
     ---@field public aggro_range integer @警戒半径
     ---@field public move_interval_ms integer @巡逻间隔毫秒
     ---@field public chase_interval_ms integer @追击间隔毫秒
     ---@field public max_chase_distance integer @最大追击距离
     ---@field public patrol_range integer @巡逻范围
     ---@field public param_1 integer @扩展参数1
     ---@field public param_2 integer @扩展参数2
     ---@field public param_3 number @扩展参数3
        local class = {
            { name='id', type='integer'},
            { name='ai_type', type='string'},
            { name='aggro_range', type='integer'},
            { name='move_interval_ms', type='integer'},
            { name='chase_interval_ms', type='integer'},
            { name='max_chase_distance', type='integer'},
            { name='patrol_range', type='integer'},
            { name='param_1', type='integer'},
            { name='param_2', type='integer'},
            { name='param_3', type='number'},
        }
        beans['common.Ai'] = class
    end
    do
    ---@class common.ChestConfig 
     ---@field public id integer @宝箱ID
     ---@field public name string @宝箱名称
     ---@field public rewards string @奖励
        local class = {
            { name='id', type='integer'},
            { name='name', type='string'},
            { name='rewards', type='string'},
        }
        beans['common.ChestConfig'] = class
    end
    do
    ---@class common.DateTimeRange 
     ---@field public start_time integer
     ---@field public end_time integer
        local class = {
            { name='start_time', type='integer'},
            { name='end_time', type='integer'},
        }
        beans['common.DateTimeRange'] = class
    end
    do
    ---@class common.FloatRange 
     ---@field public min number
     ---@field public max number
        local class = {
            { name='min', type='number'},
            { name='max', type='number'},
        }
        beans['common.FloatRange'] = class
    end
    do
    ---@class common.GlobalConfig 
     ---@field public x1 integer @背包容量
     ---@field public x2 integer
     ---@field public x3 integer
     ---@field public x4 integer
     ---@field public x5 integer
     ---@field public x6 integer
     ---@field public x7 integer[]
        local class = {
            { name='x1', type='integer'},
            { name='x2', type='integer'},
            { name='x3', type='integer'},
            { name='x4', type='integer'},
            { name='x5', type='integer'},
            { name='x6', type='integer'},
            { name='x7', type='integer[]'},
        }
        beans['common.GlobalConfig'] = class
    end
    do
    ---@class common.IntRange 
     ---@field public min integer
     ---@field public max integer
        local class = {
            { name='min', type='integer'},
            { name='max', type='integer'},
        }
        beans['common.IntRange'] = class
    end
    do
    ---@class common.MapConfig 
     ---@field public id integer @地图ID
     ---@field public map_name string @地图标识
     ---@field public display_name string @显示名称
     ---@field public width integer @地图宽度
     ---@field public height integer @地图高度
     ---@field public spawn_x integer @出生点X
     ---@field public spawn_y integer @出生点Y
        local class = {
            { name='id', type='integer'},
            { name='map_name', type='string'},
            { name='display_name', type='string'},
            { name='width', type='integer'},
            { name='height', type='integer'},
            { name='spawn_x', type='integer'},
            { name='spawn_y', type='integer'},
        }
        beans['common.MapConfig'] = class
    end
    do
    ---@class common.MapMonster 
     ---@field public id integer @配置ID
     ---@field public map_id integer @地图ID
     ---@field public monster_id integer @怪物ID
     ---@field public x integer @出生X
     ---@field public y integer @出生Y
     ---@field public respawn_time integer @重生秒数
     ---@field public is_active boolean @是否激活
     ---@field public ai_id integer @AI配置ID
        local class = {
            { name='id', type='integer'},
            { name='map_id', type='integer'},
            { name='monster_id', type='integer'},
            { name='x', type='integer'},
            { name='y', type='integer'},
            { name='respawn_time', type='integer'},
            { name='is_active', type='boolean'},
            { name='ai_id', type='integer'},
        }
        beans['common.MapMonster'] = class
    end
    do
    ---@class common.Monster 
     ---@field public id integer @怪物ID
     ---@field public name string @名称
     ---@field public level integer @等级
     ---@field public exp integer @击杀经验
     ---@field public drop_items string @掉落配置
     ---@field public attrs common.MonsterAttr[] @属性列表
        local class = {
            { name='id', type='integer'},
            { name='name', type='string'},
            { name='level', type='integer'},
            { name='exp', type='integer'},
            { name='drop_items', type='string'},
            { name='attrs', type='common.MonsterAttr[]'},
        }
        beans['common.Monster'] = class
    end
    do
    ---@class common.MonsterAttr  @怪物属性项
     ---@field public attr_key integer @属性键
     ---@field public attr_value integer @属性值
        local class = {
            { name='attr_key', type='integer'},
            { name='attr_value', type='integer'},
        }
        beans['common.MonsterAttr'] = class
    end
    do
    ---@class common.OneDayTimeRange 
     ---@field public start_time common.TimeOfDay
     ---@field public end_time common.TimeOfDay
        local class = {
            { name='start_time', type='common.TimeOfDay'},
            { name='end_time', type='common.TimeOfDay'},
        }
        beans['common.OneDayTimeRange'] = class
    end
    do
    ---@class common.RoleInitConfig 
     ---@field public id integer @配置ID
     ---@field public init_items string @初始道具
     ---@field public init_tasks string @初始任务
     ---@field public init_guide_step integer @初始引导步骤
        local class = {
            { name='id', type='integer'},
            { name='init_items', type='string'},
            { name='init_tasks', type='string'},
            { name='init_guide_step', type='integer'},
        }
        beans['common.RoleInitConfig'] = class
    end
    do
    ---@class common.TimeOfDay 
     ---@field public hour integer
     ---@field public minute integer
     ---@field public second integer
        local class = {
            { name='hour', type='integer'},
            { name='minute', type='integer'},
            { name='second', type='integer'},
        }
        beans['common.TimeOfDay'] = class
    end
    do
    ---@class item.Item 
     ---@field public id integer @道具ID
     ---@field public name string @道具名称
     ---@field public major_type integer @主类型
     ---@field public minor_type integer @子类型
     ---@field public max_pile_num integer @最大堆叠
     ---@field public quality integer @品质
     ---@field public icon string @图标
     ---@field public icon_backgroud string @图标背景
     ---@field public icon_mask string @图标遮罩
     ---@field public desc string @描述
     ---@field public show_order integer @显示顺序
     ---@field public effect_type string @效果类型
     ---@field public effect_value integer @效果数值
     ---@field public price integer @价格
     ---@field public can_sell boolean @可否出售
     ---@field public obtain_methods string @获取途径
     ---@field public release_date string @上线日期
        local class = {
            { name='id', type='integer'},
            { name='name', type='string'},
            { name='major_type', type='integer'},
            { name='minor_type', type='integer'},
            { name='max_pile_num', type='integer'},
            { name='quality', type='integer'},
            { name='icon', type='string'},
            { name='icon_backgroud', type='string'},
            { name='icon_mask', type='string'},
            { name='desc', type='string'},
            { name='show_order', type='integer'},
            { name='effect_type', type='string'},
            { name='effect_value', type='integer'},
            { name='price', type='integer'},
            { name='can_sell', type='boolean'},
            { name='obtain_methods', type='string'},
            { name='release_date', type='string'},
        }
        beans['item.Item'] = class
    end
    do
    ---@class RoleInitConfig  @角色初始配置
     ---@field public id integer @配置ID
     ---@field public init_items string @初始道具(itemId:count,itemId:count)
     ---@field public init_tasks string @初始任务(taskId,taskId)
     ---@field public init_guide_step integer @初始引导步骤
        local class = {
            { name='id', type='integer'},
            { name='init_items', type='string'},
            { name='init_tasks', type='string'},
            { name='init_guide_step', type='integer'},
        }
        beans['RoleInitConfig'] = class
    end
    do
    ---@class ServerConfig 
     ---@field public id integer @区服ID
     ---@field public server_name string @区服名称
     ---@field public host string @网关地址
     ---@field public port integer @网关端口
     ---@field public status integer @区服状态
     ---@field public is_new boolean @是否新服
     ---@field public is_recommend boolean @是否推荐
        local class = {
            { name='id', type='integer'},
            { name='server_name', type='string'},
            { name='host', type='string'},
            { name='port', type='integer'},
            { name='status', type='integer'},
            { name='is_new', type='boolean'},
            { name='is_recommend', type='boolean'},
        }
        beans['ServerConfig'] = class
    end
    do
    ---@class test.Shape 
        local class = {
        }
        beans['test.Shape'] = class
    end
    do
    ---@class test.Circle :Shape  @圆
     ---@field public radius number @半径
        local class = {
            { name='radius', type='number'},
        }
        beans['test.Circle'] = class
    end
    do
    ---@class test2.Rectangle :test.Shape  @矩形
     ---@field public width number @宽度
     ---@field public height number @高度
        local class = {
            { name='width', type='number'},
            { name='height', type='number'},
        }
        beans['test2.Rectangle'] = class
    end
    do
    ---@class test.TestExcelBean1  @这是个测试excel结构
     ---@field public x1 integer @最高品质
     ---@field public x2 string @黑色的
     ---@field public x3 integer @蓝色的
     ---@field public x4 number @最差品质
        local class = {
            { name='x1', type='integer'},
            { name='x2', type='string'},
            { name='x3', type='integer'},
            { name='x4', type='number'},
        }
        beans['test.TestExcelBean1'] = class
    end
    do
    ---@class test.TestExcelBean2  @这是个测试excel结构
     ---@field public y1 integer @最高品质
     ---@field public y2 string @黑色的
     ---@field public y3 number @蓝色的
        local class = {
            { name='y1', type='integer'},
            { name='y2', type='string'},
            { name='y3', type='number'},
        }
        beans['test.TestExcelBean2'] = class
    end
    do
    ---@class vec2 
     ---@field public x number
     ---@field public y number
        local class = {
            { name='x', type='number'},
            { name='y', type='number'},
        }
        beans['vec2'] = class
    end
    do
    ---@class vec3 
     ---@field public x number
     ---@field public y number
     ---@field public z number
        local class = {
            { name='x', type='number'},
            { name='y', type='number'},
            { name='z', type='number'},
        }
        beans['vec3'] = class
    end
    do
    ---@class vec4 
     ---@field public x number
     ---@field public y number
     ---@field public z number
     ---@field public w number
        local class = {
            { name='x', type='number'},
            { name='y', type='number'},
            { name='z', type='number'},
            { name='w', type='number'},
        }
        beans['vec4'] = class
    end

local tables =
{
    { name='TbGlobalConfig', file='common_tbglobalconfig', mode='one', value_type='common.GlobalConfig'},
    { name='TbServerConfig', file='tbserverconfig', mode='map', index='id', value_type='ServerConfig' },
    { name='TbAccountConfig', file='common_tbaccountconfig', mode='map', index='id', value_type='common.AccountConfig' },
    { name='TbAi', file='common_tbai', mode='map', index='id', value_type='common.Ai' },
    { name='TbChestConfig', file='common_tbchestconfig', mode='map', index='id', value_type='common.ChestConfig' },
    { name='TbMapConfig', file='common_tbmapconfig', mode='map', index='id', value_type='common.MapConfig' },
    { name='TbMapMonster', file='common_tbmapmonster', mode='map', index='id', value_type='common.MapMonster' },
    { name='TbMonster', file='common_tbmonster', mode='map', index='id', value_type='common.Monster' },
    { name='TbRoleInitConfig', file='common_tbroleinitconfig', mode='map', index='id', value_type='common.RoleInitConfig' },
    { name='TbItem', file='item_tbitem', mode='map', index='id', value_type='item.Item' },
}

return { enums = enums, beans = beans, tables = tables }

