// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message_id.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from message_id.proto</summary>
  public static partial class MessageIdReflection {

    #region Descriptor
    /// <summary>File descriptor for message_id.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBtZXNzYWdlX2lkLnByb3RvEghwcm90b2NvbCrDEgoJTWVzc2FnZUlkEgsK",
            "B1VOS05PV04QABIICgRQSU5HEAESCAoEUE9ORxACEhkKFUdBVEVXQVlfSEVB",
            "UlRCRUFUX1JFURBkEhkKFUdBVEVXQVlfSEVBUlRCRUFUX1JTUBBlEhcKE0dB",
            "VEVXQVlfQ09OTkVDVF9SRVEQZhIXChNHQVRFV0FZX0NPTk5FQ1RfUlNQEGcS",
            "HQoZR0FURVdBWV9ESVNDT05ORUNUX05PVElGWRBoEhcKE0dBVEVXQVlfS0lD",
            "S19OT1RJRlkQaRIcChdMT0dJTl9BQ0NPVU5UX0xPR0lOX1JFURDSARIcChdM",
            "T0dJTl9BQ0NPVU5UX0xPR0lOX1JTUBDTARIcChdMT0dJTl9TRUxFQ1RfU0VS",
            "VkVSX1JFURDUARIcChdMT0dJTl9TRUxFQ1RfU0VSVkVSX1JTUBDVARIYChNT",
            "RVJWRVJfR0VUX0xJU1RfUkVREPoBEhgKE1NFUlZFUl9HRVRfTElTVF9SU1AQ",
            "+wESGQoUU0VSVkVSX1NUQVRVU19VUERBVEUQ/AESGAoTR0FNRV9FTlRFUl9H",
            "QU1FX1JFURDAAhIYChNHQU1FX0VOVEVSX0dBTUVfUlNQEMECEhkKFEdBTUVf",
            "Q1JFQVRFX1JPTEVfUkVREMICEhkKFEdBTUVfQ1JFQVRFX1JPTEVfUlNQEMMC",
            "EhIKDUdBTUVfTU9WRV9SRVEQxAISEgoNR0FNRV9NT1ZFX1JTUBDFAhIaChVH",
            "QU1FX01PVkVfQ09ORklSTV9SRVEQxgISGwoWR0FNRV9NT1ZFX0NPTVBMRVRF",
            "X1JFURDHAhIcChdHQU1FX01PVkVfQ0FOQ0VMX05PVElGWRDIAhIfChpHQU1F",
            "X01PVkVfQ09MTElTSU9OX05PVElGWRDJAhIWChFHQU1FX1VTRV9JVEVNX1JF",
            "URDKAhIWChFHQU1FX1VTRV9JVEVNX1JTUBDLAhIXChJHQU1FX0RST1BfSVRF",
            "TV9SRVEQzAISFwoSR0FNRV9EUk9QX0lURU1fUlNQEM0CEh8KGkdBTUVfSU5W",
            "RU5UT1JZX1JFT1JERVJfUkVREM4CEh8KGkdBTUVfSU5WRU5UT1JZX1JFT1JE",
            "RVJfUlNQEM8CEhAKC0dBTUVfR01fUkVRENQCEhAKC0dBTUVfR01fUlNQENUC",
            "EhgKE0dBTUVfT1BFTl9DSEVTVF9SRVEQ3gISGAoTR0FNRV9PUEVOX0NIRVNU",
            "X1JTUBDfAhIdChhHQU1FX0NIRVNUX1VQREFURV9OT1RJRlkQ4AISHgoZR0FN",
            "RV9NQVBfSU5GT19TWU5DX05PVElGWRDoAhIYChNHQU1FX0NIQU5HRV9NQVBf",
            "UkVREOoCEhgKE0dBTUVfQ0hBTkdFX01BUF9SU1AQ6wISHQoYR0FNRV9NT05T",
            "VEVSX01PVkVfTk9USUZZEPICEiMKHkdBTUVfTU9OU1RFUl9NT1ZFX1NUQVJU",
            "X05PVElGWRDzAhIkCh9HQU1FX01PTlNURVJfTU9WRV9DQU5DRUxfTk9USUZZ",
            "EPQCEh4KGUdBTUVfTU9OU1RFUl9ERUFUSF9OT1RJRlkQ9gISIAobR0FNRV9N",
            "T05TVEVSX1JFU1BBV05fTk9USUZZEPcCEhsKFkdBTUVfQ09NQkFUX0xPR19O",
            "T1RJRlkQ/AISHQoYR0FNRV9DT01CQVRfU1RBVEVfTk9USUZZEP0CEh0KGEdB",
            "TUVfQ09NQkFUX1NUQVJUX05PVElGWRD+AhIbChZHQU1FX0NPTUJBVF9FTkRf",
            "Tk9USUZZEP8CEhwKF0dBTUVfQlVGRl9VUERBVEVfTk9USUZZEIADEhsKFkdB",
            "TUVfQ0FTVF9TVEFSVF9OT1RJRlkQqQMSHAoXR0FNRV9DQVNUX1JFU1VMVF9O",
            "T1RJRlkQqgMSHQoYR0FNRV9DT01CQVRfRVZFTlRfTk9USUZZEKsDEiEKHEdB",
            "TUVfUFJPSkVDVElMRV9TUEFXTl9OT1RJRlkQrAMSHwoaR0FNRV9QUk9KRUNU",
            "SUxFX0hJVF9OT1RJRlkQrQMSGgoVR0FNRV9ESVNFTkdBR0VfTk9USUZZEK4D",
            "EhoKFUdBTUVfUk9MRV9BVFRSX05PVElGWRD1AhIhChxHQU1FX1VQREFURV9V",
            "SV9QQU5FTF9QT1NfUkVREIYDEiEKHEdBTUVfVVBEQVRFX1VJX1BBTkVMX1BP",
            "U19SU1AQhwMSHQoYR0FNRV9QTEFZRVJfREVBVEhfTk9USUZZEIgDEhkKFEdB",
            "TUVfRVFVSVBfU0tJTExfUkVREIsDEhkKFEdBTUVfRVFVSVBfU0tJTExfUlNQ",
            "EIwDEhsKFkdBTUVfVU5FUVVJUF9TS0lMTF9SRVEQjQMSGwoWR0FNRV9VTkVR",
            "VUlQX1NLSUxMX1JTUBCOAxIhChxHQU1FX1NFVF9QUkVGRVJSRURfU0tJTExf",
            "UkVREI8DEiEKHEdBTUVfU0VUX1BSRUZFUlJFRF9TS0lMTF9SU1AQlgMSEgoN",
            "R0FNRV9DQVNUX1JFURCXAxISCg1HQU1FX0NBU1RfUlNQEJgDEh0KGEdBTUVf",
            "TlBDX0lOVEVSQUNUX05PVElGWRCQAxIYChNHQU1FX0NIQU5HRV9KT0JfUkVR",
            "EJEDEhgKE0dBTUVfQ0hBTkdFX0pPQl9SU1AQkgMSGAoTR0FNRV9OUENfQ09N",
            "QkFUX1JFURCTAxIYChNHQU1FX05QQ19DT01CQVRfUlNQEJQDEhkKFEdBTUVf",
            "TEVWRUxfVVBfTk9USUZZEJUDEhwKF0dBTUVfRU5USVRZX0xJU1RfTk9USUZZ",
            "EJoDEh4KGUdBTUVfRU5USVRZX0NSRUFURV9OT1RJRlkQmwMSHwoaR0FNRV9F",
            "TlRJVFlfREVTVFJPWV9OT1RJRlkQnAMSGwoWR0FNRV9EUk9QX1NQQVdOX05P",
            "VElGWRCkAxIcChdHQU1FX0RST1BfUElDS1VQX05PVElGWRClAxIcChdHQU1F",
            "X0RST1BfUkVNT1ZFX05PVElGWRCmAxIeChlHQU1FX0RJUkVDVElPTl9DSEFO",
            "R0VfUkVREK8DEhoKFUdBTUVfRElSRUNUSU9OX05PVElGWRCwAxIhChxHQU1F",
            "X0dFVF9TRVJWRVJfTE9HX1BBVEhfUkVRELgDEiEKHEdBTUVfR0VUX1NFUlZF",
            "Ul9MT0dfUEFUSF9SU1AQuQNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.MessageId), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///*
  /// 消息ID映射表
  /// 用于消息路由和识别
  /// </summary>
  public enum MessageId {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    /// <summary>
    /// 系统消息 (1-99)
    /// </summary>
    [pbr::OriginalName("PING")] Ping = 1,
    [pbr::OriginalName("PONG")] Pong = 2,
    /// <summary>
    /// Gateway消息 (100-199)
    /// </summary>
    [pbr::OriginalName("GATEWAY_HEARTBEAT_REQ")] GatewayHeartbeatReq = 100,
    [pbr::OriginalName("GATEWAY_HEARTBEAT_RSP")] GatewayHeartbeatRsp = 101,
    [pbr::OriginalName("GATEWAY_CONNECT_REQ")] GatewayConnectReq = 102,
    [pbr::OriginalName("GATEWAY_CONNECT_RSP")] GatewayConnectRsp = 103,
    [pbr::OriginalName("GATEWAY_DISCONNECT_NOTIFY")] GatewayDisconnectNotify = 104,
    [pbr::OriginalName("GATEWAY_KICK_NOTIFY")] GatewayKickNotify = 105,
    /// <summary>
    /// Login消息 (200-299)
    /// </summary>
    [pbr::OriginalName("LOGIN_ACCOUNT_LOGIN_REQ")] LoginAccountLoginReq = 210,
    [pbr::OriginalName("LOGIN_ACCOUNT_LOGIN_RSP")] LoginAccountLoginRsp = 211,
    [pbr::OriginalName("LOGIN_SELECT_SERVER_REQ")] LoginSelectServerReq = 212,
    [pbr::OriginalName("LOGIN_SELECT_SERVER_RSP")] LoginSelectServerRsp = 213,
    /// <summary>
    /// Server消息 (250-299)
    /// </summary>
    [pbr::OriginalName("SERVER_GET_LIST_REQ")] ServerGetListReq = 250,
    [pbr::OriginalName("SERVER_GET_LIST_RSP")] ServerGetListRsp = 251,
    [pbr::OriginalName("SERVER_STATUS_UPDATE")] ServerStatusUpdate = 252,
    /// <summary>
    /// Game消息 (300-399)
    /// </summary>
    [pbr::OriginalName("GAME_ENTER_GAME_REQ")] GameEnterGameReq = 320,
    [pbr::OriginalName("GAME_ENTER_GAME_RSP")] GameEnterGameRsp = 321,
    [pbr::OriginalName("GAME_CREATE_ROLE_REQ")] GameCreateRoleReq = 322,
    [pbr::OriginalName("GAME_CREATE_ROLE_RSP")] GameCreateRoleRsp = 323,
    [pbr::OriginalName("GAME_MOVE_REQ")] GameMoveReq = 324,
    [pbr::OriginalName("GAME_MOVE_RSP")] GameMoveRsp = 325,
    [pbr::OriginalName("GAME_MOVE_CONFIRM_REQ")] GameMoveConfirmReq = 326,
    [pbr::OriginalName("GAME_MOVE_COMPLETE_REQ")] GameMoveCompleteReq = 327,
    [pbr::OriginalName("GAME_MOVE_CANCEL_NOTIFY")] GameMoveCancelNotify = 328,
    [pbr::OriginalName("GAME_MOVE_COLLISION_NOTIFY")] GameMoveCollisionNotify = 329,
    [pbr::OriginalName("GAME_USE_ITEM_REQ")] GameUseItemReq = 330,
    [pbr::OriginalName("GAME_USE_ITEM_RSP")] GameUseItemRsp = 331,
    [pbr::OriginalName("GAME_DROP_ITEM_REQ")] GameDropItemReq = 332,
    [pbr::OriginalName("GAME_DROP_ITEM_RSP")] GameDropItemRsp = 333,
    [pbr::OriginalName("GAME_INVENTORY_REORDER_REQ")] GameInventoryReorderReq = 334,
    [pbr::OriginalName("GAME_INVENTORY_REORDER_RSP")] GameInventoryReorderRsp = 335,
    [pbr::OriginalName("GAME_GM_REQ")] GameGmReq = 340,
    [pbr::OriginalName("GAME_GM_RSP")] GameGmRsp = 341,
    /// <summary>
    /// 宝箱 (350-359)
    /// </summary>
    [pbr::OriginalName("GAME_OPEN_CHEST_REQ")] GameOpenChestReq = 350,
    [pbr::OriginalName("GAME_OPEN_CHEST_RSP")] GameOpenChestRsp = 351,
    [pbr::OriginalName("GAME_CHEST_UPDATE_NOTIFY")] GameChestUpdateNotify = 352,
    /// <summary>
    /// 地图同步 (360-369)
    /// </summary>
    [pbr::OriginalName("GAME_MAP_INFO_SYNC_NOTIFY")] GameMapInfoSyncNotify = 360,
    [pbr::OriginalName("GAME_CHANGE_MAP_REQ")] GameChangeMapReq = 362,
    [pbr::OriginalName("GAME_CHANGE_MAP_RSP")] GameChangeMapRsp = 363,
    /// <summary>
    /// 怪物AI (370-379)
    /// </summary>
    [pbr::OriginalName("GAME_MONSTER_MOVE_NOTIFY")] GameMonsterMoveNotify = 370,
    [pbr::OriginalName("GAME_MONSTER_MOVE_START_NOTIFY")] GameMonsterMoveStartNotify = 371,
    [pbr::OriginalName("GAME_MONSTER_MOVE_CANCEL_NOTIFY")] GameMonsterMoveCancelNotify = 372,
    [pbr::OriginalName("GAME_MONSTER_DEATH_NOTIFY")] GameMonsterDeathNotify = 374,
    [pbr::OriginalName("GAME_MONSTER_RESPAWN_NOTIFY")] GameMonsterRespawnNotify = 375,
    /// <summary>
    /// 战斗日志 (380-389)
    /// </summary>
    [pbr::OriginalName("GAME_COMBAT_LOG_NOTIFY")] GameCombatLogNotify = 380,
    [pbr::OriginalName("GAME_COMBAT_STATE_NOTIFY")] GameCombatStateNotify = 381,
    [pbr::OriginalName("GAME_COMBAT_START_NOTIFY")] GameCombatStartNotify = 382,
    [pbr::OriginalName("GAME_COMBAT_END_NOTIFY")] GameCombatEndNotify = 383,
    /// <summary>
    /// Buff独立通知 (384-389)
    /// </summary>
    [pbr::OriginalName("GAME_BUFF_UPDATE_NOTIFY")] GameBuffUpdateNotify = 384,
    /// <summary>
    /// 技能施法事件 (425-429)
    /// </summary>
    [pbr::OriginalName("GAME_CAST_START_NOTIFY")] GameCastStartNotify = 425,
    [pbr::OriginalName("GAME_CAST_RESULT_NOTIFY")] GameCastResultNotify = 426,
    [pbr::OriginalName("GAME_COMBAT_EVENT_NOTIFY")] GameCombatEventNotify = 427,
    [pbr::OriginalName("GAME_PROJECTILE_SPAWN_NOTIFY")] GameProjectileSpawnNotify = 428,
    [pbr::OriginalName("GAME_PROJECTILE_HIT_NOTIFY")] GameProjectileHitNotify = 429,
    [pbr::OriginalName("GAME_DISENGAGE_NOTIFY")] GameDisengageNotify = 430,
    /// <summary>
    /// 角色属性同步 (373-379)
    /// </summary>
    [pbr::OriginalName("GAME_ROLE_ATTR_NOTIFY")] GameRoleAttrNotify = 373,
    /// <summary>
    /// UI 面板位置 (390-399)
    /// </summary>
    [pbr::OriginalName("GAME_UPDATE_UI_PANEL_POS_REQ")] GameUpdateUiPanelPosReq = 390,
    [pbr::OriginalName("GAME_UPDATE_UI_PANEL_POS_RSP")] GameUpdateUiPanelPosRsp = 391,
    /// <summary>
    /// 死亡重生 (392-399)
    /// </summary>
    [pbr::OriginalName("GAME_PLAYER_DEATH_NOTIFY")] GamePlayerDeathNotify = 392,
    /// <summary>
    /// 技能系统 (395-398)
    /// </summary>
    [pbr::OriginalName("GAME_EQUIP_SKILL_REQ")] GameEquipSkillReq = 395,
    [pbr::OriginalName("GAME_EQUIP_SKILL_RSP")] GameEquipSkillRsp = 396,
    [pbr::OriginalName("GAME_UNEQUIP_SKILL_REQ")] GameUnequipSkillReq = 397,
    [pbr::OriginalName("GAME_UNEQUIP_SKILL_RSP")] GameUnequipSkillRsp = 398,
    /// <summary>
    /// 优先技能 (399)
    /// </summary>
    [pbr::OriginalName("GAME_SET_PREFERRED_SKILL_REQ")] GameSetPreferredSkillReq = 399,
    [pbr::OriginalName("GAME_SET_PREFERRED_SKILL_RSP")] GameSetPreferredSkillRsp = 406,
    /// <summary>
    /// 技能施法 (407-408)
    /// </summary>
    [pbr::OriginalName("GAME_CAST_REQ")] GameCastReq = 407,
    [pbr::OriginalName("GAME_CAST_RSP")] GameCastRsp = 408,
    /// <summary>
    /// NPC系统 (400-409)
    /// </summary>
    [pbr::OriginalName("GAME_NPC_INTERACT_NOTIFY")] GameNpcInteractNotify = 400,
    [pbr::OriginalName("GAME_CHANGE_JOB_REQ")] GameChangeJobReq = 401,
    [pbr::OriginalName("GAME_CHANGE_JOB_RSP")] GameChangeJobRsp = 402,
    [pbr::OriginalName("GAME_NPC_COMBAT_REQ")] GameNpcCombatReq = 403,
    [pbr::OriginalName("GAME_NPC_COMBAT_RSP")] GameNpcCombatRsp = 404,
    [pbr::OriginalName("GAME_LEVEL_UP_NOTIFY")] GameLevelUpNotify = 405,
    /// <summary>
    /// 统一实体系统 (410-419)
    /// </summary>
    [pbr::OriginalName("GAME_ENTITY_LIST_NOTIFY")] GameEntityListNotify = 410,
    [pbr::OriginalName("GAME_ENTITY_CREATE_NOTIFY")] GameEntityCreateNotify = 411,
    [pbr::OriginalName("GAME_ENTITY_DESTROY_NOTIFY")] GameEntityDestroyNotify = 412,
    [pbr::OriginalName("GAME_DROP_SPAWN_NOTIFY")] GameDropSpawnNotify = 420,
    [pbr::OriginalName("GAME_DROP_PICKUP_NOTIFY")] GameDropPickupNotify = 421,
    [pbr::OriginalName("GAME_DROP_REMOVE_NOTIFY")] GameDropRemoveNotify = 422,
    /// <summary>
    /// 朝向同步 (431-432)
    /// </summary>
    [pbr::OriginalName("GAME_DIRECTION_CHANGE_REQ")] GameDirectionChangeReq = 431,
    [pbr::OriginalName("GAME_DIRECTION_NOTIFY")] GameDirectionNotify = 432,
    /// <summary>
    /// 调试辅助 (440-449)
    /// </summary>
    [pbr::OriginalName("GAME_GET_SERVER_LOG_PATH_REQ")] GameGetServerLogPathReq = 440,
    [pbr::OriginalName("GAME_GET_SERVER_LOG_PATH_RSP")] GameGetServerLogPathRsp = 441,
  }

  #endregion

}

#endregion Designer generated code
