using Godot;
namespace ClinetCSharp
{
    public partial class DebugPanelUITab
    {
        public override void ConnectSignals() { if (_skillBarIconSizeSlider != null) _skillBarIconSizeSlider.ValueChanged += OnSkillBarIconSizeChanged; if (_skillBarSpacingSlider != null) _skillBarSpacingSlider.ValueChanged += OnSkillBarSpacingChanged; if (_skillBarNameFontSizeSlider != null) _skillBarNameFontSizeSlider.ValueChanged += OnSkillBarNameFontSizeChanged; if (_skillBarMarginRightSlider != null) _skillBarMarginRightSlider.ValueChanged += OnSkillBarMarginRightChanged; if (_skillBarMarginBottomSlider != null) _skillBarMarginBottomSlider.ValueChanged += OnSkillBarMarginBottomChanged; if (_fnBarOffsetXSlider != null) _fnBarOffsetXSlider.ValueChanged += OnFnBarOffsetXChanged; if (_fnBarOffsetYSlider != null) _fnBarOffsetYSlider.ValueChanged += OnFnBarOffsetYChanged; if (_fnBarSpacingSlider != null) _fnBarSpacingSlider.ValueChanged += OnFnBarSpacingChanged; if (_buffBarIconSizeSlider != null) _buffBarIconSizeSlider.ValueChanged += OnBuffBarIconSizeChanged; if (_buffBarSpacingSlider != null) _buffBarSpacingSlider.ValueChanged += OnBuffBarSpacingChanged; if (_buffBarOffsetXSlider != null) _buffBarOffsetXSlider.ValueChanged += OnBuffBarOffsetXChanged; if (_buffBarOffsetYSlider != null) _buffBarOffsetYSlider.ValueChanged += OnBuffBarOffsetYChanged; if (_buffBarRightAlignCheck != null) _buffBarRightAlignCheck.Toggled += OnBuffBarRightAlignToggled; }
        public override void DisconnectSignals() { if (_skillBarIconSizeSlider != null) _skillBarIconSizeSlider.ValueChanged -= OnSkillBarIconSizeChanged; if (_skillBarSpacingSlider != null) _skillBarSpacingSlider.ValueChanged -= OnSkillBarSpacingChanged; if (_skillBarNameFontSizeSlider != null) _skillBarNameFontSizeSlider.ValueChanged -= OnSkillBarNameFontSizeChanged; if (_skillBarMarginRightSlider != null) _skillBarMarginRightSlider.ValueChanged -= OnSkillBarMarginRightChanged; if (_skillBarMarginBottomSlider != null) _skillBarMarginBottomSlider.ValueChanged -= OnSkillBarMarginBottomChanged; if (_fnBarOffsetXSlider != null) _fnBarOffsetXSlider.ValueChanged -= OnFnBarOffsetXChanged; if (_fnBarOffsetYSlider != null) _fnBarOffsetYSlider.ValueChanged -= OnFnBarOffsetYChanged; if (_fnBarSpacingSlider != null) _fnBarSpacingSlider.ValueChanged -= OnFnBarSpacingChanged; if (_buffBarIconSizeSlider != null) _buffBarIconSizeSlider.ValueChanged -= OnBuffBarIconSizeChanged; if (_buffBarSpacingSlider != null) _buffBarSpacingSlider.ValueChanged -= OnBuffBarSpacingChanged; if (_buffBarOffsetXSlider != null) _buffBarOffsetXSlider.ValueChanged -= OnBuffBarOffsetXChanged; if (_buffBarOffsetYSlider != null) _buffBarOffsetYSlider.ValueChanged -= OnBuffBarOffsetYChanged; if (_buffBarRightAlignCheck != null) _buffBarRightAlignCheck.Toggled -= OnBuffBarRightAlignToggled; }
        private void OnSkillBarIconSizeChanged(double value) => ApplySkillBarSettings(); private void OnSkillBarSpacingChanged(double value) => ApplySkillBarSettings(); private void OnSkillBarNameFontSizeChanged(double value) => ApplySkillBarSettings(); private void OnSkillBarMarginRightChanged(double value) => ApplySkillBarSettings(); private void OnSkillBarMarginBottomChanged(double value) => ApplySkillBarSettings(); private void ApplySkillBarSettings()
        {
            var skillBar = Owner.GetTree()?.GetFirstNodeInGroup("skill_bar") as SkillBar; if (skillBar == null) return; skillBar.IconSize = (int)_skillBarIconSizeSlider.Value; skillBar.SlotSpacing = (int)_skillBarSpacingSlider.Value; skillBar.NameFontSize = (int)_skillBarNameFontSizeSlider.Value; skillBar.MarginRight = (int)_skillBarMarginRightSlider.Value; skillBar.MarginBottom = (int)_skillBarMarginBottomSlider.Value; skillBar.RebuildLayout();
        }
        private void OnFnBarOffsetXChanged(double value) => ApplyFnBarSettings(); private void OnFnBarOffsetYChanged(double value) => ApplyFnBarSettings(); private void OnFnBarSpacingChanged(double value) => ApplyFnBarSettings(); private void ApplyFnBarSettings()
        {
            var functionBar = Owner.GetTree()?.GetFirstNodeInGroup("function_bar") as FunctionButtonBar; if (functionBar == null) return; functionBar.OffsetX = (float)_fnBarOffsetXSlider.Value; functionBar.OffsetY = (float)_fnBarOffsetYSlider.Value; functionBar.ButtonSpacing = (int)_fnBarSpacingSlider.Value; functionBar.RebuildLayout();
        }
        private void OnBuffBarIconSizeChanged(double value) => ApplyBuffBarSettings(); private void OnBuffBarSpacingChanged(double value) => ApplyBuffBarSettings(); private void OnBuffBarOffsetXChanged(double value) => ApplyBuffBarSettings(); private void OnBuffBarOffsetYChanged(double value) => ApplyBuffBarSettings(); private void OnBuffBarForceShow() { var buffBar = Owner.GetTree()?.GetFirstNodeInGroup("buff_bar") as BuffBar; buffBar?.ForceShowAll(); }
        private void OnBuffBarRightAlignToggled(bool pressed)
        {
            var buffBar = Owner.GetTree()?.GetFirstNodeInGroup("buff_bar") as BuffBar; if (buffBar == null) return; buffBar.RightAlign = pressed; buffBar.RebuildLayout();
        }
        private void ApplyBuffBarSettings()
        {
            var buffBar = Owner.GetTree()?.GetFirstNodeInGroup("buff_bar") as BuffBar; if (buffBar == null) return; buffBar.IconSize = (int)_buffBarIconSizeSlider.Value; buffBar.SlotSpacing = (int)_buffBarSpacingSlider.Value; buffBar.OffsetX = (int)_buffBarOffsetXSlider.Value; buffBar.OffsetY = (int)_buffBarOffsetYSlider.Value; buffBar.RightAlign = _buffBarRightAlignCheck?.ButtonPressed ?? false; buffBar.RebuildLayout();
        }
    }
}